### ISSUE TITLE
Feature request: can be set environment variable from envFrom in k6 CR.

### ISSUE THREAD

**Issue by mugioka** [grafana/k6-operator#122]
# motivation
When executing k6 scripts, we need to handle sensitive information such as API Key in environment variables, but currently we cannot define environment variables in envFrom, so we are having trouble handling sensitive information.
By enabling envFrom to be used with k6 CR, secret information can be managed with secret resources, making it possible to handle secret information more securely.

**Comment by BarthV** [comment]
https://github.com/grafana/k6-operator/blob/main/api/v1alpha1/k6_types.go#L53-L65

K6 specs `Runner` key is a standard kubernetes pod spec, So you can perfectly add standard pod env specs usign any existing configMap or Secret.

An example from my own test suites :
```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6
spec:
  parallelism: 2
  script:
    localFile: /k6/pipeline.js
  arguments: --stage 120s:180 --stage 300s:360 --stage 420s:360 --stage 60s:0
  runner:
    env:
    - name: FOOBAR
      value: http://foor.far
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: my-api-secret
          key: secret
    - name: SOME_VAR
      value: any-value
```
