### ISSUE TITLE
No resources.limits.cpu defined on k6-curl container (starter pod)

### ISSUE THREAD

**Issue by mikeja67** [grafana/k6-operator#136]
Hello,

Version: 0.0.7
In production, when I started a CRD k6, I had an error due to gatekeeper:
_Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [container-must-have-limits] container <k6-curl> has no cpu limit._

So the pod *--starter that synchronize injector's pods with curl never started.

I see in associated job that resources was defined like this:

```
    image: docker-ghcr-proxy.repository.pole-emploi.intra/grafana/operator:latest-starter
    imagePullPolicy: IfNotPresent
    name: k6-curl
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 2Mi
```

**So no cpu limits defined (sic!)**

find in:
_pkg/resources/containers/curl.go_
```
        return corev1.Container{
                Name:  "k6-curl",
                Image: image,
                Env:   env,
                Resources: corev1.ResourceRequirements{
                        Requests: corev1.ResourceList{
                                corev1.ResourceCPU:    *resource.NewMilliQuantity(50, resource.DecimalSI),
                                corev1.ResourceMemory: *resource.NewQuantity(2097152, resource.BinarySI),
                        },
                        Limits: corev1.ResourceList{
                                corev1.ResourceMemory: *resource.NewQuantity(209715200, resource.BinarySI),
                        },

```
I tried to patch myself by adding the new line  (same as request ;-))
```
make delete
make deploy
```
but no better...

Can you give me a workaround (I'm not GO developer)?

Best regards

Claude
