### ISSUE TITLE
Add flexibility to the path of the script

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#143]
Currently, k6-operator with `ConfigMap` and `VolumeClaim` options expects JS script to be present in `/test` folder:
https://github.com/grafana/k6-operator/blob/de5794766160bca70dfb8a06e6868b0ae8aa2c86/pkg/types/types.go#L22-L57

These two options don't match how `LocalFile` is implemented and it also [causes issues](https://community.k6.io/t/loading-custom-module-bundles-with-operator/4231/5) during usage.

Caveat: in order not to break anyone's existing setup, it'd be good to keep backwards-compatibility with the current approach.

**Comment by moko-poi** [comment]
Hi! @yorugac 
I've implemented a solution for this issue and opened a PR: #641 

## Summary of Changes

Added an optional `path` field to both `K6Configmap` and `K6VolumeClaim` structs that allows users to specify custom mount paths for their script files.

## Key Features

- **Backward compatible**: When `path` is not specified, it defaults to `/test/` (current behavior)
- **Flexible configuration**: Users can now specify custom paths like `/custom/scripts/`
- **Consistent with LocalFile**: Aligns the behavior across all script source types
- **Path normalization**: Automatically ensures paths end with `/` for consistency

## Example Usage

```yaml
# Custom path
apiVersion: k6.io/v1alpha1
kind: TestRun
spec:
  script:
    configMap:
      name: test-scripts
      file: load-test.js
      path: /custom/scripts  # New optional field

# Default behavior (backward compatible)
apiVersion: k6.io/v1alpha1
kind: TestRun
spec:
  script:
    configMap:
      name: test-scripts
      file: load-test.js
      # No path specified - defaults to /test/
```

## Testing

I've tested both scenarios locally:
- ✅ Custom path configuration works correctly
- ✅ Default behavior maintains backward compatibility
- ✅ No breaking changes for existing setups

The implementation should address the inconsistency with `LocalFile` while preserving existing functionality. Would love to get feedback on the approach!
