### ISSUE TITLE
RBAC Permissions seem excessive

### ISSUE THREAD

**Issue by ghostsquad** [grafana/k6-operator#150]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k6-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s/status
  - k6s/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
```

This seems dangerous. Can documentation be provided to show how these permissions may be more restricted?

**Comment by yorugac** [comment]
Just a note; it's quite likely that using operator with `--out cloud` option and without it can have different lists of RBAC. If so, it makes sense to check all RBAC and make separate lists.

**Comment by realHarter** [comment]
Are there any news yet? I'm looking for a way to deploy the operator + all tests in a single namespace with no access rights outside this namespace.

**Comment by yorugac** [comment]
@realHarter, this issue is more about validation and documentation rather than any specific changes. But it's quite possible to deploy k6-operator and the tests in the same namespace as it is. Have you encountered an issue while trying to do that?

**Comment by realHarter** [comment]
@yorugac I haven't tested alot yet. But so far it's working for me after rewriting all ClusterRoles to Roles, declaring the crds as namespaced and setting the `WATCH_NAMESPACE` env variable to the single namespace I'm deploying too.

**Comment by yorugac** [comment]
Thanks for details. A guide for such a setup would likely be nice :+1:

**Comment by ichasepucks** [comment]
@yorugac when you say
> But it's quite possible to deploy k6-operator and the tests in the same namespace as it is.

Were you expecting this to be done by changing configuration as @realHarter did or is there a cleaner way with `kustomize` to do this?  I'm just playing with `kustomize` for the first time today so I haven't yet determined if this is possible.

**Comment by rafedbenjeddou** [comment]
> @yorugac I haven't tested alot yet. But so far it's working for me after rewriting all ClusterRoles to Roles, declaring the crds as namespaced and setting the `WATCH_NAMESPACE` env variable to the single namespace I'm deploying too.

Hello @realHarter, can you provide me the manifest file with this changes please ? thank you

**Comment by FloGro3** [comment]
I can confirm @realHarter's approach. Well I didn't have to adapt the CRDs because in the latest helm release they already have the scope "Namespaced". The only things that needed to be changed was to change the clusterRole to role (just change Kind from ClusterRole to Role and add the namespace (and also adapt the connected clusterBinding -> same approach):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k6-operator.fullname" . }}-manager-role
  namespace: {{- include "k6-operator.namespace" . }}
...
```
Setting the env variable was also necessary. I added that to the deployment.yaml so that it is set automatically for each env the k6-operator is deployed to. Just under "env" on the "manager" container add this:

```
env:
  - name: WATCH_NAMESPACE
    value: {{- include "k6-operator.namespace" . }}
```
