### ISSUE TITLE
tar archive is created on /home/k6 instead of tmp

### ISSUE THREAD

**Issue by rgordill** [grafana/k6-operator#160]
### Brief summary

That means user should be 65534 or have access rights to that folder.

https://github.com/grafana/k6-operator/blob/main/pkg/resources/jobs/initializer.go#L57

If it is created in /tmp folder, any user could run the tests without any particular uid privilege.

### k6-operator version or image

latest (8.0.0rc3)

### K6 YAML

```yaml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample-with-extensions
  namespace: k6-tests
spec:
  parallelism: 4
  script:
    configMap:
      name: sample-stress-test
      file: test.js
  arguments: --http-debug -o output-prometheus-remote
  runner:
    image: xxxx:latest
```

### Steps to reproduce the problem

Run k6 tests from a namespace with restricted users. For example

  securityContext:
    runAsUser: 1000

### Expected behaviour

Archive stored and read successfully.

### Actual behaviour

Permission denied errors.
