### ISSUE TITLE
Pass environment variables to k6 arguments

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#162]
### Feature Description

At the moment, to pass environment variable as part of `arguments` string in k6-operator, one has to use external tooling, scripts, etc.
Kubernetes supports passing environment variables as [argument for pods](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments) with specific format. Its equivalent in k6 CRD would be something like this:
```
arguments: --tag pod="$(HOSTNAME)"
runner:
  env:
      - name: HOSTNAME
        value: ...
```

Attempt to use the above snippet results in k6 error due to escaped double quotes in `--tag` option:
```
time="2022-10-31T14:16:36Z" level=error msg="invalid argument \"pod=\\\"bar\\\"\" for \"--tag\" flag: parse error on line 1, column 5: bare \" in non-quoted-field"
```

Find solution to pass environment variables in `arguments` of k6 CRD.

### Suggested Solution (optional)

Adding support for passing environment variables in the above format would mean parsing `arguments` string in full and removing unnecessary escapes for `--tag`.
Alternatively, establish another approach to pass environment variables to `arguments` in k6-operator.

### Already existing or connected issues / PRs (optional)

This came up in forum question: https://community.k6.io/t/k6-operator-pass-local-environment-variable-as-test-wide-tag/5015

**Comment by yorugac** [comment]
In PR https://github.com/grafana/k6-operator/pull/839, I've been figuring out a "safe" passing of env vars and added a "full" fix for initializer pod on the way. Now this form is safe to set:
```yaml
   spec:
     arguments: -e GREETING=$(MY_GREETING)
     runner:
       env:
         - name: MY_GREETING
           value: "hello world with spaces"
```
Note: the quotes in `env[].value` are for correct YAML formatting; but the value itself is stored unquoted. It is safe to pass it to `.spec.arguments` because it's passed to pods and then expanded by kubelet.

With the PR https://github.com/grafana/k6-operator/pull/839, this syntax for env vars is now substituted with `"${MY_GREETING}"` specifically for the initializer Shell script, which is then properly expanded as env var in `sh -c`. Previously, it could cause an error from initializer.

The same approach can be extended to the tags: substituting the syntax for initializer to allow format like `arguments: --tag pod=$(HOSTNAME)`. 

_What if I need to pass the actual quote symbol?_ You can pass it in pod's env var like this: `value: 'say "hi"'`. Plus it's also possible to pass it in `arguments` literally just as before. What you can't do in `arguments` is pass _spaces_ as those would be misinterpreted as delimiters of arguments. So to have spaces, you have to use the env var expansion as shown above.

I wonder if the scope of this issue should be changed now. For example, document the above and add syntax substitution in initializer for tags. Anything else?

**Comment by yorugac** [comment]
There was another round of refactoring that essentially negates the [above comment](https://github.com/grafana/k6-operator/issues/162#issuecomment-4967449312) 😅 The trick with additional env vars is certainly helpful, but when there are a lot of values, its value becomes questionable: it's less readable and it pollutes the pod spec a bit too much.

So intead, in https://github.com/grafana/k6-operator/pull/868, there was an addition of `.spec.args` field in `TestRun` CRD that allows to pass arbitrary values to k6 as is, with minimal interference from k6-operator:
```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample-with-args
spec:
  parallelism: 2
  script:
    configMap:
      name: k6-test
      file: test.js
  args:
    - --tag
    - note=arbitrary values are possible "here"  # passed to k6 as is
    - -e
    - PRICE_LABEL=$$100 # passed to k6 as is
    - -e
    - BASE_URL=$(BASE_URL) # Kubernetes env var will be expanded
  runner:
    env:
      - name: BASE_URL
        value: https://test.k6.io
```

This change was released as part of https://github.com/grafana/k6-operator/releases/tag/v1.6.0

With this, I believe this issue can be closed:
- Kubernetes env var expansion works as is
- It's now possible to pass arbitrary strings and values, without bothering with quotes

If someone disagrees and there is another use case still not covered by `.spec.args`, please share!
