### ISSUE TITLE
CSV/Json output is broken when running 5 parallel scripts

### ISSUE THREAD

**Issue by andreiopr** [grafana/k6-operator#163]
### Brief summary

CSV/Json output is broken when running a script on 5 pods

Some of the output rows are added in the middle or at the end of an existing row.
E.g. `http_req_waiting,1666866258,79.782394,,true,,GET,https://appsevus,1666866258,0.000000,,,,,,,,,instance_id=2&job_name=k6-sample-2` Notice that `vus` was inserted in the middle of an URL
I think the issue occurs because all pods are trying to write in the same file at the same time.

A solution would be to provide a way to generate a separate output for every pod

### k6-operator version or image

latest (8.0.0rc3)

### K6 YAML

```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 5
  script:
    volumeClaim:
      name: k6-pvc
      file: test.js
  arguments: --out csv=/test/Test.csv
  separate: true
```

### Steps to reproduce the problem

- run a k6 script using the k6 operator with `parallelism: 5` and output set for csv `--out csv=/test/Test.csv`
- open the csv output
- search for `vus` until you find a row where `vus` is added in the middle or at the end of the row

### Expected behaviour

All rows in the output are displayed correctly.

### Actual behaviour

Output is broken, some rows are added over other rows.
