### ISSUE TITLE
Starter doesn’t work in an IPv6 cluster

### ISSUE THREAD

**Issue by yann-soubeyrand** [grafana/k6-operator#171]
### Brief summary

In an IPv6 cluster, the starter pod logs this error:
```
curl: (3) IPv6 numerical address used in URL without brackets
```

### k6-operator version or image

latest

### K6 YAML

```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: load-test
  namespace: load-testing
spec:
  parallelism: 100
  script:
    configMap:
      name: load-test
      file: load-test.js
  separate: true
  runner:
    resources:
      requests:
        cpu: 1
        memory: 4G
```

### Steps to reproduce the problem

Create an IPv6 cluster on AWS EKS, deploy the operator inside and start a test.

### Expected behaviour

The test run as expected.

### Actual behaviour

The test doesn’t start because the operator doesn’t seem to handle IPv6.
