### ISSUE TITLE
Scuttle Logging cannot be disabled

### ISSUE THREAD

**Issue by cogren1** [grafana/k6-operator#179]
### Brief summary

Scuttle enables logging by default. This is problem because its logs end up in the initializer logs, causing the operator to be unable to unmarshal it into JSON. Adding `scuttleLogging: false` does not work though because the controller does not insert environment variables into the pod spec when their value evaluates to false. This applies to all boolean Scuttle parameters, but it's only a problem for scuttleLogging because default value in Scuttle is true.

Here is the offending line: https://github.com/grafana/k6-operator/blob/main/pkg/resources/jobs/helpers.go#L87

You can see that it checks for a value that evaluates to false instead of checking for the _presence_ of the parameter. I've tested this with scuttleLogging and neverKillIstioOnFailure. When true, the environment variable is present. When false, they are not present. These, and other scuttle values, are defined as boolean in the CRD, which seems unnecessary since the values get converted to strings when inserted as pod environment variables and is one of the reasons this bug occurs.

### k6-operator version or image

v0.0.9rc1, v0.0.8, v0.0.8rc3, v0.0.8rc2, v0.0.8rc1, v0.0.7, v0.0.7rc4, v0.0.7rc3, v0.0.7rc2, v0.0.7rc

### K6 YAML

``` yaml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: load-test
  namespace: k6-operator-system
spec:
  parallelism: 10
  runner:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
  scuttle:
    enabled: "true"
    envoyAdminApi: 'http://127.0.0.1:15000'
    istioQuitApi: 'http://127.0.0.1:15020'
    scuttleLogging: false
  script:
    configMap:
      name: test-cm
      file: test.js
```

### Other environment details (if applicable)

Istio is installed.

### Steps to reproduce the problem

On a cluster with Istio installed:
1. Create a test config map.
2. Create a K6 object with the following scuttle and runner settings:
    ``` yaml
      runner:
        metadata:
          labels:
            sidecar.istio.io/inject: "true"
      scuttle:
        enabled: "true"
        scuttleLogging: false
    ```

### Expected behaviour

`SCUTTLE_LOGGING` appears in the initializer pod spec under `env` with value `"false"`.

### Actual behaviour

`SCUTTLE_LOGGING` does not appear in the initializer pod spec.
