### ISSUE TITLE
Add notification support

### ISSUE THREAD

**Issue by simskij** [grafana/k6-operator#2]
The operator should be able to send notifications upon starting and finishing test runs.
To get a lot of options with little work, we should use https://github.com/containrrr/shoutrrr.

Configuration of notifications should be done by deploying a notification CR.
Some kind of draft proposal of how this could look:

```yaml
apiVersion: k6.io/v1alpha1
kind: K6Notification
metadata:
  name: k6-notification
spec:
  start:
    - some://shoutrrr/url
  finish:
    - some://shoutrrr/url
  error:
    - some://shoutrrr/url
```
