### ISSUE TITLE
Support runners in specified namespace

### ISSUE THREAD

**Issue by thestevenbell** [grafana/k6-operator#205]
Requesting the ability to execute test runner pods in specified namespace.

```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6
  namespace: 	k6-operator-system
spec:
  parallelism: 1
  script:
    configMap:
      file: test.js
  arguments: --tag testid=k6-output-grafana-9 --out experimental-prometheus-rw
  runner:
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://sre-kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090/api/v1/write
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "false"
      - name: K6_PROMETHEUS_RW_STALE_MARKERS
        value: "true"
      - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
        value: 2s
    metadata:
      namespace: sre
```

```
error: error validating "k8s/k6s.yaml": error validating data: ValidationError(K6.spec.runner.metadata): unknown field "namespace" in io.k6.v1alpha1.K6.spec.runner.metadata; if you choose to ignore these errors, turn validation off with --validate=false
```
