### ISSUE TITLE
Cannot pass env vars to k6 tests via k6-operator resource

### ISSUE THREAD

**Issue by danielfigueiredo** [grafana/k6-operator#207]
### Brief summary

Hey team, I've been trying to get my k6 tests running via k8s using the `k6-operator`, but I'm unable to pass any environment variables.

I've looked in detail at the community forum and demo app, and whatever syntax is there does not seem to work for me.
The runnerSpec go file seems to forward the `env` vars declared within the `spec.runner`. However, my tests keep failing right when bootstrapping because the vars provided are unavailable.

I've tried several syntax combinations with different indentations, some of them failed to be parsed, and all others do not throw errors, but they don't seem to work either.

### k6-operator version or image

`make deploy` executed from commit sha `151472705d2e35d1c6d9158affed2ab127c305ba` (latest in the repo main branch at time of writing)

### K6 YAML
```yml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-distributed
spec:
  parallelism: 4
  script:
    configMap:
      name: my-test-file-dev
      file: my-test-file-dev.js
  runner:
    image: danielfigueiredoc/demo-k6-operator:latest
    env:
      - name: REMOTE_ENV
        value: staging
```

### Steps to reproduce the problem

My docker file is the same as the demo / recommended in k6-operator docs
```
FROM golang:1.19-alpine as builder
WORKDIR $GOPATH/src/go.k6.io/k6
ADD . .
RUN apk --no-cache add git
RUN CGO_ENABLED=0 go install go.k6.io/xk6/cmd/xk6@latest
# TODO - Want more extensions?! Provide additional `--with ...` lines to the following command:
RUN CGO_ENABLED=0 xk6 build \
    --output /tmp/k6

FROM alpine:3.16
RUN apk add --no-cache ca-certificates \
    && adduser -D -u 12345 -g 12345 k6
COPY --from=builder /tmp/k6 /usr/bin/k6

USER 12345
WORKDIR /home/k6

ENTRYPOINT ["k6"]
```

It is all very simple; tests run fine without env var assertions. But I added this check when my test bootstraps:
```js
import { fail } from 'k6';
//  ...

const env = __ENV.REMOTE_ENV;

if (!env) {
  fail('no REMOTE_ENV given');
}
```
When I run `kubectl apply -f ./path/to/k6-resource.yml` the `k6-distributed-initializer` job kicks in, I can see the pod being created and immediately failing with:
```
time="2023-03-22T15:05:41Z" level=error msg="GoError: no REMOTE_ENV given\n\tat go.k6.io/k6/js/modules/k6.(*K6).Fail-fm (native)\n\tat getRemoteEnv (file:///....)
```

If I swap the script with a sample test requiring no env vars, it works fine. 
Everybody seems to provide the env vars as I do, so I think something is up with my setup that I can't figure out yet. 

I've also tried to provide env vars via config map but got the same behaviour: there are no failures when running the command, but tests crash as env vars are unavailable. I swapped the `runner.env` with this:

```yml
  envFrom:
  - configMapRef:
      name: trade-mobile-sessions-dev-env-vars
```

Any help would be much appreciated; I'm not sure what's going on. The only difference between my code and https://github.com/javaducky/demo-k6-operator is that I create my local cluster using `minikube`, which should not matter theoretically.

### Expected behaviour

Be able to provide env vars somehow to the k6 tests being executed.

### Actual behaviour

Env vars are not available.

**Comment by danielfigueiredo** [comment]
I finally discovered the issue; it appears that when running k6 through the operator + k8s the environment variables are only available at a different time.
The test case I was trying to run had the static `options` const referencing environment variables such as:

```js
// common file
function getRemoteEnv() {
  const env = __ENV.REMOTE_ENV;

  if (!env) {
    fail('no REMOTE_ENV given');
  }

  return env;
}

// test file imports getRemoteEnv from common file
export const options = {
  vus: 10,
  duration: '10s',
  thresholds: {
    'http_reqs{expected_response:true}': ['rate>10'],
  },
  tags: {
    env: getRemoteEnv(),
  }
};
```

We used to run k6 via nomad, and this evaluation works fine, but running this way this env var is not yet available. It is after because I can see it when logging within the test case or within the setup function call.
I don't fully understand why yet, but at least the problem is solved!

**Comment by yorugac** [comment]
Hi @danielfigueiredo, thanks for opening the issue! Could you please try the following simple example:

```
---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 1
  script:
    configMap:
      name: "env-vars"
      file: "env-var.js"
  cleanup: "post"
  runner:
    env:
      - name: REMOTE_ENV
        value: staging
```
and 
```
import { sleep } from 'k6';

export let options = {
    vus: 10,
    duration: '30s',
    discardResponseBodies: true,
};

// Run with:
// k6 run -e REMOTE_ENV=something env-var.js

const testvar = __ENV.REMOTE_ENV;

export default function () {
    console.log("testvar is", testvar);
    console.log("env var is", __ENV.REMOTE_ENV);
    sleep(1);
}
```
So without custom images and complex outputs. The above works for me. Would these work in your setup? I think it makes sense to go step by step to figure out at which point the issue appears: right now it's not clear :sweat_smile:
