### ISSUE TITLE
`leases.coordination.k8s.io` retrieval error

### ISSUE THREAD

**Issue by prmmuthu** [grafana/k6-operator#224]
### Brief summary

Hello All,

We are using k6 operator for the past 6 months, but now our tests are not picked up by k6 operator and getting below error even after restarting the pods.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/31092316/235303436-7d03a1db-0de2-4e06-b726-12c4460d06fb.png">

### k6-operator version or image

v0.0.8

### K6 YAML
```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-test1-1682685331
  namespace: k6-operator-system
spec:
  parallelism: 1
  script:
    volumeClaim:
      name: k6-pvc
      file: 50.tar
  arguments: --tag test_id=50 --tag region=westeurope --tag provider=azure --tag platform_name=tse
    --tag product_id=test1 --tag env=prod --tag app=loadstar
  runner:
    image: crgazwe.azurecr.io/k6test
    imagePullSecrets:
    - name: k6-cred
    env:
    - name: K6_OUT
      value: xk6-prometheus-rw
    - name: K6_LOG_OUTPUT
      value: "loki=https://<...>:<...>@telemetry.pensieve.maersk-digital.net/loki/api/v1/push,label.app_name=50,label.region=westeurope,label.provider=azure,label.product_id=test1,label.env=prod,label.app=loadstar,allowedLabels=[region,provider,product_id,env,app,app_name]"
    - name: K6_PROMETHEUS_RW_SERVER_URL
      value: https://telemetry.pensieve.maersk-digital.net/api/v1/push
    - name: K6_PROMETHEUS_RW_TREND_STATS
      value: "avg,p(90),p(99),min,max"
    - name: K6_PROMETHEUS_RW_HEADERS_AUTHORIZATION
      value: Bearer <...>
    - name: K6_STAGES
      value: 2m:1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 300Mi
```

### Steps to reproduce the problem

Can be reproduced by using the same version

### Expected behaviour

Need to elect the leader without error and start the k6 test

### Actual behaviour

leader election failing
