### ISSUE TITLE
Add PrivateLoadZone CRD

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#227]
Define and add PrivateLoadZone CRD following this approximate spec:

```
apiVersion: k6.io/v1alpha1
kind: PrivateLoadZone
metadata:
  name: amazing-plz
spec:
  token: cloud-token # mandatory
  resources: # mandatory
    cpu: ...
    memory: ...
  serviceAccountName: ... # or default
  nodeSelector: # or nil
    foo: bar
```

Subtasks:

- [X] Support loading token with the name in addition to labels.
- [X] Add PLZRegistered and CloudPLZTestRun conditions.
- [X] Once registered and if polling is not running, start the polling.
- [X] Polling test runs, sending to the channel. Create K6 resource for each test run.
- [X] On deletion of PLZ, call deregister.
- [X] Pass additional fields of PLZ CRD to K6 CRD.
