### ISSUE TITLE
Multi-Cluster Execution

### ISSUE THREAD

**Issue by evanfpearson** [grafana/k6-operator#240]
### Feature Description

I have the requirement to run a load test across more than one cluster. An update to the Operator and CRD should make this possible, potentially with the addition of another CRD. I don't have an exact solution yet, but I think it would be doable and worth discussing here.

### Suggested Solution (optional)

The K6 CRD can be updated to accept some new variable e.g., clusters:

``` 
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
  namespace: k6
spec:
  parallelism: 2
  clusters:
    - name: trundle
      proportion: 50%
    - name: michu
      proportion: 50%
  script:
    configMap:
      name: archive
      file: archive.tar
```

This would start two pods, one in the `trundle` cluster and and one in the `michu` cluster. Roles on those clusters will need to be added allowing:
- management of jobs (e.g., for starting runner pods)
- management of services
- access to the service proxy (so the paused k6 processes can be started)

The k6-operator's access to these clusters can be defined using a new custom resource, e.g, `K6Cluster`:

```
apiVersion: k6.io/v1alpha1
kind: K6Cluster
metadata:
  name: trundle
  namespace: k6
spec:
  namespace: k6
  kubeconfig:
    secretRef:
      name: trundle-kubeconfig
    configMap:
      name: archive
      file: archive.tar
```

The kubeconfig secret will need to have access information for the cluster:

```
apiVersion: v1
data:
  ca.crt: LS0tLS1C...0tLQo=
  namespace: azYK
  token: ZXlKaGJH...0NV9LY0NFX1E=
kind: Secret
metadata:
  name: trundle-kubeconfig
  namespace: k6
type: kubernetes.io/service-account-token
```

When the k6-operator reconciles a new `K6` resource, it will first check that `K6Cluster` resources exist for the named clusters in the `K6` resource. Then clients will be created for each of those clusters so the necessary jobs can be created. 

Obviously this will be a fairly big change in the operator and I may not have considered everything, but I'm happy to discuss in more detail.
