### ISSUE TITLE
K6 Operator Not Picking Up Changes to image

### ISSUE THREAD

**Issue by c1moore** [grafana/k6-operator#266]
### Brief summary

Hey all, I'm trying to get a CI/CD pipeline working to run K6 tests in Kubernetes.  We have a bit of a complicated use case, so wanted to go the path of adding our tests to a Docker image and uploading it to ECR.  Our Dockerfile looks something like this

```dockerfile
FROM grafana/k6:latest

COPY ./dist/main.js /test/

# Some additional config...

ENV K6_STATSD_ENABLE_TAGS=true
```

Once the docker image has been uploaded, we use the following base yaml file to create/update a CR:

```yaml
apiVersion: k6.io/v1alpha1
kind: K6

metadata:
  name: restaurant-pos-load-test

spec:
  parallelism: 4
  separate: true
  script:
    localFile: /test/main.js
  runner:
    image: $DOCKER_IMAGE
```

The `$DOCKER_IMAGE` is replaced at build time using `envsubst` once we know the tag used to create the docker image.

This worked once and that's it.  It seems like the k6 operator is not checking for changes to the `runner.image` field.

### k6-operator version or image

0.0.9

### K6 YAML

```yaml
apiVersion: k6.io/v1alpha1
kind: K6

metadata:
  name: restaurant-pos-load-test

spec:
  parallelism: 4
  separate: true
  script:
    localFile: /test/main.js
  runner:
    image: $DOCKER_IMAGE
```

### Steps to reproduce the problem

1. Create a custom resource => it runs
3. Update the Docker image referenced in the custom resource and apply => nothing happens

### Expected behaviour

When the docker image is updated, K6 pulls the new image and reruns the tests.

### Actual behaviour

After updating the Docker image, k6 operator doesn't detect the change or at least doesn't trigger a run of the tests.

**Comment by c1moore** [comment]
To add some details, here's an example of the first K6 YAML:

```yaml
apiVersion: k6.io/v1alpha1
kind: K6

metadata:
  name: restaurant-pos-load-test

spec:
  parallelism: 4
  separate: true
  script:
    localFile: /test/main.js
  runner:
    image: *********.dkr.ecr.us-east-1.amazonaws.com/restaurant-pos-load-test:61a62e4f3026
```

And here's the latest one I tried to run

```yaml
apiVersion: k6.io/v1alpha1
kind: K6

metadata:
  name: restaurant-pos-load-test

spec:
  parallelism: 4
  separate: true
  script:
    localFile: /test/main.js
  runner:
    image: *********.dkr.ecr.us-east-1.amazonaws.com/restaurant-pos-load-test:828459ab922d_61a62e4f3026_5790497466_1
```

Looking at `kubectl get pod <podName> -o yaml`, I'm noticing the image hasn't been updated

```
    image: 656168747096.dkr.ecr.us-east-1.amazonaws.com/restaurant-pos-load-test:61a62e4f3026
    imagePullPolicy: IfNotPresent
```
