### ISSUE TITLE
Publish Helm chart on releases

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#277]
### Feature Description

There should be a CI workflow on k6-operator releases publishing Helm chart to the repository.

### Suggested Solution (optional)

It appears that all (?) Grafana Helm charts are published here:
https://grafana.github.io/helm-charts/

These can likely be used as code references:
- https://github.com/grafana/helm-charts/blob/main/.github/workflows/update-helm-repo.yaml
- https://github.com/grafana/agent/blob/main/.github/workflows/helm-release.yml

### Already existing or connected issues / PRs (optional)

Depends on:
- PR #98 being merged

**Comment by mladenrtl** [comment]
I have the same question. I am waiting this to be released to helm-charts repository, so I can use it as dependency in our GitOps project, like:
```
dependencies:
  - name: k6-operator
    version: 1.0.0
    repository: https://grafana.github.io/helm-charts
    alias: k6-operator
```
I tried to use this but I am getting error:
`helm dependency build failed exit status 1: Error: k6-operator chart not found in repo https://grafana.github.io/helm-charts`
