### ISSUE TITLE
Node-Selector is not working

### ISSUE THREAD

**Issue by shaochun0530** [grafana/k6-operator#293]
### Brief summary

i have add nodeSelector on both runner and starter.
How ever when the runner pod is created the node selector was added in the pod spec.

### k6-operator version or image

v0.0.10 (i've benn using the lastest helm version)

### K6 YAML

```
apiVersion: k6.io/v1alpha1

kind: K6

metadata:

  name: run-k6-from-configmap

spec:

  parallelism: 4

  script:

    configMap:

      name: my-test

      file: test.js
   runner:
     nodeSelector:
       hello: "true"
```

### Steps to reproduce the problem

kubectl apply -f k6.yaml
kubectl delete -f k6.yaml

### Expected behaviour

to create runner pod with nodeSelector

### Actual behaviour

default nodeSelector
