### ISSUE TITLE
Failures of default liveness / readiness probes

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#306]
Several times we have received reports of failing default liveness and readiness probes which leads to runners not reaching ready state:
```
  Normal   Created    3m2s                   kubelet            Created container k6
  Normal   Started    3m2s                   kubelet            Started container k6
  Warning  Unhealthy  2m34s (x7 over 3m1s)   kubelet            Readiness probe failed: Get "http://10.1.0.75:6565/v1/status": dial tcp 10.1.0.75:6565: connect: connection refused
  Warning  Unhealthy  2m34s (x3 over 2m54s)  kubelet            Liveness probe failed: Get "http://10.1.0.75:6565/v1/status": dial tcp 10.1.0.75:6565: connect: connection refused
  Normal   Killing    2m34s                  kubelet            Stopping container k6
```
Such error does not allow to start the test and the test is stuck (at the moment, but this part will likely change as result of https://github.com/grafana/k6-operator/issues/260).

Default probes are the same defaults that are set by Kubernetes, i.e. k6-operator does not add anything by itself. k6 HTTP starts pretty quickly for most tests and it should be well reachable with default settings normally. The most confounding part is that this failures seemed to have been reported while using simple and basic setups of Kubernetes, even local clusters.

So far it is not clear how to repeat this case. If someone knows a trick how to repeat this, please share in this issue.

cc @dgzlopes

**Comment by Re3v3s** [comment]
I face this issue also , anyone help please

**Comment by frittentheke** [comment]
1. These probes are added here: https://github.com/grafana/k6-operator/blob/40dce3ffc13c55fb665c41b891c1459d3ad66068/pkg/resources/jobs/runner.go#L188-L189
2. Using the helper https://github.com/grafana/k6-operator/blob/40dce3ffc13c55fb665c41b891c1459d3ad66068/pkg/resources/jobs/runner.go#L279 which targets the status endpoint of the K6 REST API - https://k6.io/docs/misc/k6-rest-api/#get-status

3. Since there are no options set for the probe (apart from the HTTP destination to be used) the default timeouts are applied: 
```
[...]
    livenessProbe:                                                                                                                                                                                                                                                                       
      failureThreshold: 3                                                                                                                                                                                                                                                                
      httpGet:                                                                                                                                                                                                                                                                           
        path: /v1/status                                                                                                                                                                                                                                                                 
        port: 6565                                                                                                                                                                                                                                                                       
        scheme: HTTP                                                                                                                                                                                                                                                                     
      periodSeconds: 10                                                                                                                                                                                                                                                                  
      successThreshold: 1                                                                                                                                                                                                                                                                
      timeoutSeconds: 1

    readinessProbe:                                                                                                                                                                                                                                                                      
      failureThreshold: 3                                                                                                                                                                                                                                                                
      httpGet:                                                                                                                                                                                                                                                                           
        path: /v1/status                                                                                                                                                                                                                                                                 
        port: 6565                                                                                                                                                                                                                                                                       
        scheme: HTTP                                                                                                                                                                                                                                                                     
      periodSeconds: 10                                                                                                                                                                                                                                                                  
      successThreshold: 1                                                                                                                                                                                                                                                                
      timeoutSeconds: 1
[...]      
```
which are very likely a little too aggressive?

4. I am wondering what good the readiness probe does here currently anyways, since the operating is actually using the Pod status of `running` (https://github.com/grafana/k6-operator/blob/40dce3ffc13c55fb665c41b891c1459d3ad66068/controllers/k6_start.go#L51) to determine when to send the start command. But since a running pod is not a `ready` application it might make sense to switch to using the readiness.

5. Regarding fixing this issue here, I shall push a PR to increase the timeouts a little.
