### ISSUE TITLE
Investigate CI tests with Helm

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#311]
`helm/kind-action` that we currently use in our CI does not seem to allow to pass a verison of Kubernetes (i.e. kind image). The sample [workflow](https://github.com/grafana/k6-operator/actions/runs/6512492225/job/17690286747) with error looks this:

![Image](https://github.com/grafana/k6-operator/assets/2552297/44b76684-1f76-4ae3-a132-e75947ab75e9)

The CI in [e2e-test.yaml](https://github.com/grafana/k6-operator/blob/main/.github/workflows/e2e-test.yaml#L61) at the time of this workflow had the following:
```yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: "kindest/node:v1.27.1"
```

Find out what is causing the error and make an appropriate fix.
