### ISSUE TITLE
Suggestions for chart versioning and release management

### ISSUE THREAD

**Issue by illrill** [grafana/k6-operator#344]
### Feature Description

**Release notes**

Would like some type of chart release notes. Bare minimum populate `What's Changed` in the Github release, in the same way as the `grafana` and `loki-distributed` charts do it by just referencing PRs.

In addition to referencing PRs under `What's Changed`, there could be a custom release note annotation in Chart.yaml. When a contributor creates a new version, they also overwrite the "old" release notes with the release notes applicable for this version. This could get picked up by the helm chart releaser workflow and included in the Github release. Something like this:

```
version: 3.2.1
[...]
annotations:
  changes: |
    - kind: added
      description: Description of something I added in this version
    - kind: changed
      description: Description of something I modified in this version
```

- With prefixes adhering to https://keepachangelog.com/en/1.1.0/
- This approach is how argo-helm handles publishing of release notes to artifacthub. For example https://github.com/argoproj/argo-helm/pull/2367/files.

**Versioning**

Maybe it's on its way in #330, but some guidance and enforcement of chart versioning would be good. Again, perhaps we could use argo-helm's [guidelines](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning) as inspiration.
