### ISSUE TITLE
custom images built using xk6 don't run if you start TestRun in custom namespace

### ISSUE THREAD

**Issue by srintern** [grafana/k6-operator#355]
### Brief summary

If you built a custom image using xk6 following [these](https://github.com/grafana/k6-operator?tab=readme-ov-file#using-extensions) steps in a custom namespace, the initializer pod errors with the log: `sh: syntax error: unexpected "("`

### k6-operator version or image

latest

### TestRun / PrivateLoadZone YAML

```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample-with-extensions
spec:
  parallelism: 4
  script:
    configMap:
      name: crocodile-stress-test
      file: test.js
  runner:
    image: k6-extended:local
```

### Steps to reproduce the problem

Just follow the steps in the `README.md`

### Expected behaviour

Tests should run

### Actual behaviour

Test does not start as the initializer returns an error.
