### ISSUE TITLE
Initializer fails on --execution-requirements

### ISSUE THREAD

**Issue by YuriiBudnyi** [grafana/k6-operator#375]
### Brief summary

Hello Team. We only started to use K6 Operator in our environment. But we have an issue with Initializer, it fails on --execution-requirements if we have in test.js `const Users = __ENV.USERS.split(" ");` for example. The issue could be fixed if I add `--execution-requirements --include-system-env-vars` but I don't see possibility of changing Initializer command.

### k6-operator version or image

0.0.13

### Helm chart version (if applicable)

3.5.0

### TestRun / PrivateLoadZone YAML

```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: test-k6
spec:
  cleanup: post
  initializer:
    envFrom:
      - secretRef:
          name: test-secrets
  parallelism: 1
  runner:
    envFrom:
      - secretRef:
          name: test-secrets
  script:
    configMap:
      file: test.js
      name: load-test
  separate: false

```

### Steps to reproduce the problem

Create test.js file with const Users = __ENV.USERS.split(" ");  
export USERS="TEST1 TEST2";
Run k6 inspect --execution-requirements test.js will result in error TypeError: Cannot read property 'split' of undefined or null
Run k6 inspect --execution-requirements --include-system-env-vars test.js result without errors

### Expected behaviour

Initializer not fails

### Actual behaviour

Initializer fails
