### ISSUE TITLE
PrivateLoadZone resources should be immutable in CRD

### ISSUE THREAD

**Issue by bizrad** [grafana/k6-operator#382]
### Brief summary

The documentation in [step 4 on the procedure on this page](https://grafana.com/docs/grafana-cloud/k6/author-run/private-load-zone-v2/#create-the-plz-crd) says the following about the PLZ resources
> Note that currently, resources can only be configured during the creation of a Private Load Zone. You’ll have to delete and create a new Private Load Zone if you’d like to update your configuration.

Based on this the CRD should enforce immutability on these fields so that systems like flux can use the [force annotation](https://fluxcd.io/flux/components/kustomize/kustomizations/#kustomizetoolkitfluxcdioforce) to cause the resource to be deleted and recreated on change to the field.

This can be achieved with [k8s CRD transition rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#transition-rules)

Proposed change to https://github.com/grafana/k6-operator/blob/main/charts/k6-operator/templates/crds/plz.yaml adding the `x-kubernetes-validations` field as shown.

```
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                    x-kubernetes-validations:
                      - rule: "self.foo == oldSelf.foo"
                        message: Requests and limits can only be set during initial object creation. Delete and recreate the object to adjust.
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                    x-kubernetes-validations:
                      - rule: "self.foo == oldSelf.foo"
                        message: Requests and limits can only be set during initial object creation. Delete and recreate the object to adjust.
```

### k6-operator version or image

ghcr.io/grafana/k6-operator:controller-v0.0.13

### Helm chart version (if applicable)

3.5.0

### TestRun / PrivateLoadZone YAML

```
apiVersion: k6.io/v1alpha1
kind: PrivateLoadZone
metadata:
  name: ldev
  namespace: k6-plz
spec:
  token: grafana-k6-token
  resources:
    limits:
      cpu: 256m
      memory: 1024Mi
```

### Steps to reproduce the problem

Manually edit a PrivateLoadZone and see no error or warning is raised

### Expected behaviour

Fields cannot effect change without object replacement are immutable.

### Actual behaviour

Changing fields appears to work
