### ISSUE TITLE
Cannot run k6-operator "exec /manager: exec format error"

### ISSUE THREAD

**Issue by danielfigueiredo** [grafana/k6-operator#383]
### Brief summary

I've tried installing the `k6-operator` both via helm (latst version `3.5.0.`) or via `make deploy` using latest master. Both way produce the exact same error.

The manager pod fails to start with error, however `kube-rbac-proxy` start just fine. 

I'm running on a mac `aarch64-darwin` system

### k6-operator version or image

latest master

### Helm chart version (if applicable)

3.5.0

### TestRun / PrivateLoadZone YAML

```yml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: crocodile-stress-test
      file: single-request.js
```

### Steps to reproduce the problem

1. start brand new minikube cluster
2. install k6-operator (either way `make deploy` of master or `helm install ....` as per `README.md`)
3. Check `k6-operator-controller-manager`, status is `CrashLoopBackOff`
4. Look up logs for the manager pod to find the following error:

```
manager exec /manager: exec format error  
Stream closed EOF for k6-operator-system/k6-operator-controller-manager-645f98f9d9-487fz                                                 
```
No errors during install or anything, it only fails booting up.

### Expected behaviour

The resources required by the `k6-operator` bootstraps fine and reliably when using later or main versions. 

### Actual behaviour

`manager` status on fresh install on fresh cluster is `CrashLoopBackOff` with error `manager exec /manager: exec format error`

**Comment by danielfigueiredo** [comment]
Not sure if related, but I've been looking at the repo and it seems to be related to this line https://github.com/grafana/k6-operator/blob/main/config/manager/manager.yaml#L30

**Comment by danielfigueiredo** [comment]
Tried spinning up a local cluster using `kind` instead of `minikube`, but same error:

https://github.com/grafana/k6-operator/assets/6464911/9f5467ed-44ad-4401-a46d-d1b804b7399b

**Comment by yorugac** [comment]
Hi @danielfigueiredo! 

> I'm running on a mac aarch64-darwin system

This is ARM arch, right? If so, we have an issue for that here https://github.com/grafana/k6-operator/issues/187
And there has been a PR recently:
https://github.com/grafana/k6-operator/pull/380

I'll try to ping the author there as it's been awhile. But he has the image built there: could you please check if it works for you? It'd be helpful to confirm for your platform.

**Comment by audacioustux** [comment]
Hi, @danielfigueiredo you may try this repo, and let me know if it works out for you.
https://github.com/audacioustux/k6-operator

Example TestRun manifest:
```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: gpa-lt-closed
spec:
  parallelism: 5
  starter:
    image: ghcr.io/audacioustux/k6-operator:starter-latest
    imagePullPolicy: Always
  runner:
    image: ghcr.io/audacioustux/k6-operator:runner-latest
    imagePullPolicy: Always
  arguments: --out cloud
  script:
    configMap:
      name: gpa-lt
      file: gpa-lt.js
```
