### ISSUE TITLE
Created resources not cleaned up when TestRun is deleted

### ISSUE THREAD

**Issue by petermajn** [grafana/k6-operator#400]
### Brief summary

I installed the operator as described in the README using the bundle (https://github.com/grafana/k6-operator?tab=readme-ov-file#bundle-deployment).
I am able to run a test, but when the TestRun resource is deleted (either manually or using `cleanup: "post"`) the corresponding Jobs, Pods and Services are not deleted.

### k6-operator version or image

ghcr.io/grafana/k6-operator:controller-v0.0.14

### TestRun / PrivateLoadZone YAML
```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-example-test
  namespace: k6-tests
spec:
  parallelism: 3
  script:
    configMap:
      name: k6-example-test
      file: k6-test.js
  cleanup: "post"
```

### Steps to reproduce the problem

Apply the TestRun and wait for the created jobs to finish.

### Expected behaviour

The operator deletes all created resources when the `TestRun` resource is deleted.

### Actual behaviour

Created Jobs, Pods and Services do not get deleted. `TestRun` resource is deleted.
