### ISSUE TITLE
How to Add Custom Labels to Sender Pods with K6?

### ISSUE THREAD

**Issue by GotoRen** [grafana/k6-operator#436]
### Feature Description

This can be beneficial for cost analysis in specific environments. (ex. [GKE cost allocation](https://cloud.google.com/kubernetes-engine/docs/how-to/cost-allocations))
As a reference, the current implementation seems to assign fixed labels to the generated Pods.

- https://github.com/grafana/k6-operator/blob/f737f896054a3ac4918e727e13b044351d058872/controllers/common.go#L38-L40

Is there a way to label the Sender Pods using the K6 custom resource manifest? If this operation cannot be natively supported, what workarounds are available?

**Comment by yorugac** [comment]
Hi @GotoRen, sorry for the delay! I believe you're looking for `spec.runner.metadata.labels`:
```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 1
  script:
    configMap:
      name: "test"
      file: "test.js"
  runner:
    metadata:
      labels:
        foo: bar
```

I'm closing this issue for now, but feel free to re-open if needed!
