### ISSUE TITLE
Unable to send K6 metrics to Mimir endpoint using prometheusremotewrite

### ISSUE THREAD

**Issue by harishkumarrajasekaran** [grafana/k6-operator#472]
**Error Message**

```
running (0m05.0s), 100/100 VUs, 2374 complete and 0 interrupted iterations
default   [   2% ] 100 VUs  0m05.0s/5m0s
time="2024-10-04T03:38:06Z" level=error msg="Failed to send the time series data to the endpoint" error="got status code: 401 instead expected a 2xx successful status code" output="Prometheus remote write"
``` 

**k6-operator version or image**
0.0.16

**Helm chart version (if applicable)**
3.8.0

**TestRun / PrivateLoadZone YAML**
Testrun

**Other environment details (if applicable)**
No response

**Steps to reproduce the problem**
The following yaml file can be used to reproduce the problem.

**SECRET CREATION**
```
kubectl create secret generic mimir-auth-secret -n k6-system \
  --from-literal=K6_PROMETHEUS_RW_SERVER_URL="http://<IP-ADDRESS>:80/api/v1/write" \ 
  --from-literal=K6_PROMETHEUS_RW_USERNAME="admin" \
  --from-literal=K6_PROMETHEUS_RW_PASSWORD="<redacted>" \
  --from-literal=K6_PROMETHEUS_RW_HTTP_HEADERS="X-Scope-OrgID:k6" \
  --from-literal=K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM="true"
``` 

I have also tried server URL as mentioned in mimir [documentation ](https://grafana.com/docs/mimir/latest/get-started/#configure-prometheus-to-write-to-grafana-mimir)

http://IP-ADDRESS:80/api/v1/push

Same error getting reported.

![Image](https://github.com/user-attachments/assets/417ca60b-d3f4-41fa-8bd9-f91577f96572)

**CONFIGMAP.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: k6-system
data:
  test.js: |
    import http from 'k6/http';
    import { check } from 'k6';

    export let options = {
      vus: 100,
      duration: '300s',
    };

    export default function () {
      let res = http.get('https://test.k6.io');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
    }

``` 

**POD.yaml**

```
apiVersion: v1
kind: Pod
metadata:
  name: k6-mimir-pod
  namespace: k6-system
spec:
  containers:
  - name: k6
    image: ghcr.io/grafana/k6:latest
    command: ["k6", "run", "/test/test.js"]
    args:
      - --out
      - experimental-prometheus-rw
    env:
    - name: K6_PROMETHEUS_RW_SERVER_URL
      valueFrom:
        secretKeyRef:
          name: mimir-auth-secret
          key: K6_PROMETHEUS_RW_SERVER_URL
    - name: K6_PROMETHEUS_RW_USERNAME
      valueFrom:
        secretKeyRef:
          name: mimir-auth-secret
          key: K6_PROMETHEUS_RW_USERNAME
    - name: K6_PROMETHEUS_RW_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mimir-auth-secret
          key: K6_PROMETHEUS_RW_PASSWORD
    - name: K6_PROMETHEUS_RW_HTTP_HEADERS
      valueFrom:
        secretKeyRef:
          name: mimir-auth-secret
          key: K6_PROMETHEUS_RW_HTTP_HEADERS
    - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
      valueFrom:
        secretKeyRef:
          name: mimir-auth-secret
          key: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
    volumeMounts:
    - name: k6-test-volume
      mountPath: /test
  volumes:
  - name: k6-test-volume
    configMap:
      name: k6-test-script
  restartPolicy: Never
```
