### ISSUE TITLE
Cannot write to InfluxDB v2.

### ISSUE THREAD

**Issue by githubeto** [grafana/k6-operator#475]
I am building the image using xk6-output-influxdb, but when I run the TestRun, the following error logs are output in the Pod logs.
As a result, I cannot view the test results on Grafana.

Dockerfile
```
FROM golang:1.22-alpine3.20 as builder
WORKDIR $GOPATH/src/go.k6.io/k6
ADD . .
RUN apk --no-cache add git
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN go mod init k6
RUN xk6 build --with github.com/grafana/xk6-output-influxdb@latest --output /tmp/k6

FROM alpine:3.20
RUN apk add --no-cache ca-certificates && \
    adduser -D -u 12345 -g 12345 k6
COPY --from=builder /tmp/k6 /usr/bin/k6

USER 12345
WORKDIR /home/k6
COPY script /home/k6
ENTRYPOINT ["k6"]
```

TestRun
```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-test
  namespace: k6-operator
spec:
  arguments: --out influxdb=http://influxdb-influxdb2.k6-operator/loadtest
  parallelism: 2
  runner:
    image: xxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/loadtest:main-abd7c786
    envFrom:
      - configMapRef:
          name: k6-configmap
      - secretRef:
          name: k6-secrets
  script:
    localFile: /home/k6/test.js
```

Error logs
```
level=error msg="Couldn't write stats, InfluxDB v2.x isn't supported by this output, if you are using it you may consider to use the extension https://github.com/grafana/xk6-output-influxdb" error="{\"code\":\"unauthorized\",\"message\":\"unauthorized access\"}" output=InfluxDBv1
```

Configmap
```
apiVersion: v1
data:
  K6_INFLUXDB_BUCKET: default
  K6_INFLUXDB_CONCURRENT_WRITES: "4"
  K6_INFLUXDB_ORGANIZATION: influxdata
  K6_INFLUXDB_PRECISION: 1ns
  K6_INFLUXDB_PUSH_INTERVAL: 1s
  K6_INFLUXDB_TAGS_AS_FIELDS: vu:int,iter:int,url
kind: ConfigMap
metadata:
  ...
```

Secrets
```
apiVersion: v1
data:
  K6_INFLUXDB_INSECURE: dHJ1ZQ==
  K6_INFLUXDB_TOKEN: xxxxxxxxxxxx
kind: Secret
metadata:
  ...
type: Opaque
```
