### ISSUE TITLE
Jobs don't start

### ISSUE THREAD

**Issue by kotyara85** [grafana/k6-operator#513]
### Brief summary

Hello everyone,
Here's my test config:

Only one pod is created and the operator is complaining on this - 
```
2024-12-21T20:22:48Z	ERROR	Reconciler error	{"controller": "testrun", "controllerGroup": "k6.io", "controllerKind": "TestRun", "TestRun": {"name":"test","namespace":"k6"}, "namespace": "k6", "name": "test", "reconcileID": "0ea50705-3aea-4613-8350-39fa2161c3e4", "error": "job with the name test-1 exists; make sure you've deleted your previous run"}
```

I did delete all previous jobs before starting the test. Any help is appreciated

### k6-operator version or image

v0.0.18

### TestRun / PrivateLoadZone YAML

```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: test
  namespace: k6
spec:
  parallelism: 100
  script:
    configMap:
      name: test
      file: script.js
  runner:
    resources:
      requests:
        cpu: 100m
        memory: "128Mi"
      limits:
        cpu: "12"
        memory: 16Gi
    image: ghcr.io/grafana/k6-operator:latest-runner
  starter:
    resources:
      requests:
        cpu: 100m
        memory: "128Mi"
      limits:
        cpu: "12"
        memory: 16Gi
    image: ghcr.io/grafana/k6-operator:latest-starter
  arguments: --verbose
```

### Steps to reproduce the problem

Install operator
Try to run tests

### Expected behaviour

Tests to run

### Actual behaviour

Tests do not start
