### ISSUE TITLE
"no matches for kind \"K6\" in sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1" even with TestRun usage

### ISSUE THREAD

**Issue by robooo** [grafana/k6-operator#518]
### Brief summary

Hi,
I'm deploying operator with terraform like:
```
resource "helm_release" "k6-operator" {                                                                                                                                                                              
  name = "k6-operator"                                                                                                                                                                                               
                                                                                                                                                                                                                     
  repository = "https://grafana.github.io/helm-charts"                                                                                                                                                               
  chart = "k6-operator"   
```

and kubernetes deployment starts with:
```
apiVersion: k6.io/v1alpha1                                                                                                                                                                                           
kind: TestRun                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                            
  name: k6-testrun-se                                                                                                                                                                                                
  namespace: default                                                                                                                                                                                                 
spec:
``` 

It was working until today, I'm getting error:
```
 manager 2025-01-24T16:05:42Z    ERROR    Reconciler error    {"controller": "testrun", "controllerGroup": "k6.io", "controllerKind": "TestRun", "TestRun": {"name":"k6-testrun-se","namespace":"default"}, "names │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler                                                                                                                │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316                                                                                                          │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem                                                                                                             │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263                                                                                                          │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2                                                                                                                   │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224                                                                                                          │
│ manager 2025-01-24T16:05:42Z    INFO    controllers.TestRun    Reconcile(); stage = initialized    {"namespace": "default", "name": "k6-testrun-se", "reconcileID": "71ec2f55-3233-44e9-8678-31243ffd4e75"}       │
│ manager 2025-01-24T16:05:42Z    INFO    controllers.TestRun    Creating test jobs    {"namespace": "default", "name": "k6-testrun-se", "reconcileID": "71ec2f55-3233-44e9-8678-31243ffd4e75"}                     │
│ manager 2025-01-24T16:05:42Z    INFO    controllers.TestRun    job with the name k6-testrun-se-1 exists; make sure you've deleted your previous run    {"namespace": "default", "name": "k6-testrun-se", "reconci │
│ manager 2025-01-24T16:05:42Z    ERROR    Reconciler error    {"controller": "testrun", "controllerGroup": "k6.io", "controllerKind": "TestRun", "TestRun": {"name":"k6-testrun-se","namespace":"default"}, "names │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler                                                                                                                │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316                                                                                                          │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem                                                                                                             │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263                                                                                                          │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2                                                                                                                   │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224                                                                                                          │
│ manager 2025-01-24T16:05:51Z    ERROR    controller-runtime.source.EventHandler    if kind is a CRD, it should be installed before calling Start    {"kind": "K6.k6.io", "error": "no matches for kind \"K6\" in  │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1                                                                                                                             │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/source/kind.go:71                                                                                                                     │
│ manager k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2                                                                                                                                         │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/loop.go:87                                                                                                                                      │
│ manager k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext                                                                                                                                               │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/loop.go:88                                                                                                                                      │
│ manager k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel                                                                                                                                                  │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/poll.go:33                                                                                                                                      │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1                                                                                                                               │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/source/kind.go:64     
```

what is wrong here please?

### k6-operator version or image

ghcr.io/grafana/k6-operator:controller-v0.0.18

### Helm chart version (if applicable)

3.10.2

### TestRun / PrivateLoadZone YAML

apiVersion: k6.io/v1alpha1                                                                                                                                                                                           
kind: TestRun                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                            
  name: k6-testrun-se                                                                                                                                                                                                
  namespace: default                                                                                                                                                                                                 
spec:

### Other environment details (if applicable)

_No response_

### Steps to reproduce the problem

- Deploy the operator via terraform
- use included testrun kubernetes file

### Expected behaviour

Deployment should run with no error

### Actual behaviour

Getting error
"no matches for kind \"K6\" in sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1" even with TestRun usage
