### ISSUE TITLE
JSON schema validation error when used as subchart

### ISSUE THREAD

**Issue by illrill** [grafana/k6-operator#528]
### Brief summary

Since introducing the values schema (#432), the k6-operator chart can no longer be used as a Helm dependency (sub chart). This is because the schema doesn't allow us to provide additional values to "our own" parent chart using e.g. `Values.global`

This has happened in many other projects, see:
(issue) https://github.com/istio/istio/issues/35495 + (fix) https://github.com/istio/istio/pull/36896
(issue) https://github.com/loft-sh/vcluster/issues/1651 + (fix) https://github.com/loft-sh/vcluster/pull/1652
(fix) https://github.com/signalfx/splunk-otel-collector-chart/pull/330

For more context see https://github.com/helm/helm/issues/10392

### k6-operator version or image

v0.0.19

### Helm chart version (if applicable)

3.11.0

### TestRun / PrivateLoadZone YAML

N/A

### Steps to reproduce the problem

charts/k6/Chart.yaml
```yaml
apiVersion: v2
name: k6
type: application
version: 1.0.0
dependencies:
  - name: k6-operator
    version: 3.11.0
    repository: https://grafana.github.io/helm-charts/
```
charts/k6/values.yaml
```yaml
k6-operator:
  installCRDs: true
  namespace:
    create: false
  prometheus:
    enabled: true
```
env/production/values.yaml
```
global:
  cloudProvider: azure
  cloudRegion: westeurope
  clusterName: my-cluster
  environmentName: production
```

Command
```
$ helm dependency update charts/k6
$ helm template k6 charts/k6 --values env/production/values.yaml --values charts/k6/values.yaml
```

### Expected behaviour

I should be able to provide my own global values for my parent chart

### Actual behaviour

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
k6-operator:
- global: Additional property clusterName is not allowed
- global: Additional property cloudProvider is not allowed
- global: Additional property cloudRegion is not allowed
- global: Additional property environmentName is not allowed
```
