### ISSUE TITLE
Unable to use custom image to run test with k6/x/remotewrite

### ISSUE THREAD

**Issue by ankense-cariad** [grafana/k6-operator#537]
### Brief summary

I have a k6 test that is configured for use with [k6/x/remotewrite](https://github.com/grafana/xk6-client-prometheus-remote/blob/main/README.md). It works when I run k6 locally with the xk6 packages installed via go, but when I try to run the test with k6-operator the runner fails with the following error:

`time="2025-03-20T20:51:03Z" level=error msg="GoError: unknown module: k6/x/remotewrite\n" hint="script exception" `

Is there a way to use a custom image for the k6-operator runner (i.e. one that has xk6-client-prometheus-remote, xk6-loki modeles) so that the runner recognizes the modules? We have tried adding an `image` tag in the TestRun file directly below, but when the chart renders and gets deployed the pod always has the default image. 

### k6-operator version or image

ghcr.io/grafana/k6-operator:controller-v0.0.17,  ghcr.io/grafana/k6-operator:latest-runne

### Helm chart version (if applicable)

3.9.0

### TestRun YAML
```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-mimir-k6-test
  namespace: o11y-test
spec:
  parallelism: 2
  script:
    configMap:
      name: o11y-mimir-write-test
      file: mimir-write-load.js
  initializer:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  starter:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  runner:
    image: <my-custom-image>
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
```

### Steps to reproduce the problem

Follow the instructions in Grafana docs: https://grafana.com/docs/k6/latest/testing-guides/running-distributed-tests/#1-install-the-operator

- Configure a test that includes the xk6 client.
- Create a TestRun Object in k8s cluster
- try to load custom image by modifying the runner spec
- The runner pod will fail with unknown module error

### Expected behaviour

Expectation is that supported xk6 modules are already available in the base image, or a custom image can be used in place of the default image. 

### Actual behaviour

It is not clear if xk6 (or other additional modules) can be added to k6-operator base image or specifically to the runner component and using the runner image tag doesn't work.
