### ISSUE TITLE
Add support for secrets in `PrivateLoadZone`

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#540]
### Feature Description

Sometimes secrets should be referenced by k6 PLZ tests but also remain on the infra of the user. So [cloud env vars](https://grafana.com/docs/grafana-cloud/testing/k6/author-run/cloud-scripting-extras/cloud-environment-variables/) are insufficient for such cases.

Add support for such cases in `PrivateLoadZone` with approx. the following format:

```yaml
apiVersion: k6.io/v1alpha1
kind: PrivateLoadZone
metadata:
  name: im
  namespace: foo
spec:
  token: grafana-k6-token
  resources:
    limits:
      cpu: 256m
      memory: 1024Mi

  config:
    secrets:
      - secretRef: # pass as envFrom to all pods running k6
          name: env-secrets
      - configMapRef: # pass as envFrom to all pods running k6
          name: env-configmap
```
