### ISSUE TITLE
Cloud tests are timing out when CR is removed

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#542]
### Brief summary

If the TestRun CR is removed, all the jobs are being removed as a consequence. In case of cloud test runs (cloud output and PLZ), this is handled without communication to the GCk6, leading to the test run entering Timed Out state eventually.

### k6-operator version or image

latest

### TestRun / PrivateLoadZone YAML

```yaml
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: "test"
      file: "test.js"
  arguments: --out cloud
```

### Steps to reproduce the problem

Removing CR during test execution leads to the Timed Out.

### Expected behaviour

This case should likely be considered as "Aborted" (Aborted by user, currently). Error message about "TestRun was removed manually" would be nice.

### Actual behaviour

![Image](https://github.com/user-attachments/assets/aefdeaac-5c32-4e4d-9963-ede7b0b1b87d)
