### ISSUE TITLE
Dynamic resource loading not working

### ISSUE THREAD

**Issue by geNAZt** [grafana/k6-operator#546]
### Brief summary

We have tests which load options based on what we call "load-profiles". Those are json files which get loaded during runtime.

This works fine with the current approach of using a github runner running locally installed k6 but trying to get this to work with the operator (since we also want to test internal k8s services going forward) we hit a roadblock here.

The error we are seeing is this:

time="2025-04-09T15:06:32Z" level=error msg="TypeError: Not a function: [object Object]\n\tat loadProfileOptions (file:///tests/fire-brigade/01_keycloak.test.ts.js:72:45(14))\n\tat file:///tests/fire-brigade/01_keycloak.test.ts.js:96:33(72)\n\tat file:///tests/fire-brigade/01_keycloak.test.ts.js:120:12(3)\n" hi │
│ nt="script exception"

The lines 72 

```
var fs_namespaceObject = require("k6/x/fs");
var fs_default = /*#__PURE__*/__webpack_require__.n(fs_namespaceObject);

var profile = JSON.parse(open(fs_default()("load-profiles/".concat(__ENV.LOAD_PROFILE, ".json"))));  # This is line 72
  return {
    scenarios: {
      token: {
        executor: 'ramping-arrival-rate',
        stages: profile.stages.map(function (stage) {
          delete stage.stage;
          return stage;
        }),
        preAllocatedVUs: profile.vus.min,
        maxVUs: profile.vus.max
      }
    }
  };
```

Our custom runner image:

```
# Build the k6 binary with the extension
FROM golang:1.24 as builder

RUN go install go.k6.io/xk6/cmd/xk6@latest

COPY modules /modules

# For our example, we'll add support for output of test metrics to InfluxDB v2.
# Feel free to add other extensions using the '--with ...'.
RUN xk6 build \
    --with github.com/paymenttools/xk6-ed25519@v0.1.0=/modules/ed25519 \
    --with github.com/paymenttools/xk6-tcp@v0.1.0=/modules/tcp \
    --with github.com/paymenttools/xk6-fs@v0.1.0=/modules/fs \
    --with github.com/oleiade/xk6-kv \
    --output /k6

# Use the operator's base image and override the k6 binary
FROM grafana/k6:latest
COPY --from=builder /k6 /usr/bin/k6

COPY dist /tests
COPY load-profiles /load-profiles
COPY assets /assets

COPY --from=kvij/scuttle:latest scuttle /bin/scuttle
```

The xk6 module "fs" implementing search like this:

```
func (mi *ModuleInstance) Search(file string) *sobek.Object {
	for i := 0; i < 255; i++ {
		filePath, err := filepath.Abs(filepath.Join(strings.Repeat("../", i), file))
		if err != nil {
			common.Throw(mi.vu.Runtime(), err)
			return nil
		}

		if filePath == "/"+file {
			common.Throw(mi.vu.Runtime(), errors.New("file not found"))
			return nil
		}

		if _, err := os.Stat(filePath); err == nil {
			return mi.vu.Runtime().ToValue(filePath).ToObject(mi.vu.Runtime())
		}
	}

	common.Throw(mi.vu.Runtime(), errors.New("file not found"))
	return nil
}
````

### k6-operator version or image

0.0.19

### Helm chart version (if applicable)

3.11.1

### TestRun / PrivateLoadZone YAML

```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
  namespace: loadtest
spec:
  # cleanup: 'post'
  scuttle:
    enabled: "true"
  parallelism: 4
  script:
    localFile: /tests/fire-brigade/01_keycloak.test.ts.js
  separate: false
  arguments: "-o experimental-prometheus-rw --compatibility-mode=base"
  runner:
    image: europe-west1-docker.pkg.dev/pt-cicd/docker-snapshots/loadtest@sha256:9c5303b32afe2b7d8e4c2310c52d1efa9900e96309a13d6997208b2217e38c6f
    nodeSelector:
      cloud.google.com/gke-nodepool: loadtest
    tolerations:
    - key: "loadtest"
      operator: "Exists"
      effect: "NoSchedule"
    env:
      - name: LOAD_PROFILE
        value: "500-ramp-spike"
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://mimir.write.o11y.internal:8080/api/v1/push"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"
      - name: ENV_PROFILE
        value: "dev"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 1000m
        memory: 1000Mi
```

### Steps to reproduce the problem

Have a test loading a dynamic file with open()

### Expected behaviour

It should work since the file is backed to the runner image

### Actual behaviour

Crash with non meaningful log
