### ISSUE TITLE
Default paused behavior doesn't match documentation

### ISSUE THREAD

**Issue by scottiedog45** [grafana/k6-operator#575]
### Brief summary

The [documentation](https://grafana.com/docs/k6/latest/using-k6/k6-options/reference/#paused) seems to indicate that `paused` is false by default, but in the source code, [it's true by default](https://github.com/grafana/k6-operator/blob/14179cb9052fa0cead148d40e1f6cbaf421a2837/pkg/resources/jobs/runner.go#L61).

### k6-operator version or image

main

### TestRun / PrivateLoadZone YAML

```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-testrun
spec:
  paused: "false"
  # create 4 containers taking 25% of the total job each
  parallelism: 4
  # remove all containers upon test completion
#  cleanup: "post"
  script:
    configMap:
      name: k6-configmap
      file: test.js
  # test-id is used to filter out test results in Datadog
  arguments: "--verbose"
  runner:
    serviceAccountName: k6-test-runner
    volumeMounts:
      - mountPath: /tmp
        name: tmp-volume
    volumes:
      - name: tmp-volume
        emptyDir: {}
    securityContext:
      runAsGroup: 12345
      runAsNonRoot: true
      runAsUser: 12345
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
  starter:
    serviceAccountName: k6-test-runner
    volumeMounts:
      - mountPath: /tmp
        name: tmp-volume
    volumes:
      - name: tmp-volume
        emptyDir: {}
    securityContext:
      runAsGroup: 12345
      runAsNonRoot: true
      runAsUser: 12345
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
```

### Steps to reproduce the problem

Deploy a `TestRun` with a k6 test embedded in a configMap, and the test will pause after initializing.

### Expected behaviour

Either the docs need to be updated, or the default needs to change to false.

### Actual behaviour

Tests are paused after init, after applying `TestRun`.
