### ISSUE TITLE
No logs in log file if the runs fails at initializer level

### ISSUE THREAD

**Issue by vipul-mykaarma** [grafana/k6-operator#581]
### Brief summary

hi all,
Whenever there is some error in script and the k6 log output is set to file I doot see nay logs  in the file . Everytime I have i to change the log ouput stodut to check for any errors in intializer pod 

### k6-operator version or image

0.0.18

### TestRun / PrivateLoadZone YAML

```
name: run-k6
      inputs: {}
      outputs: {}
      metadata: {}
      resource:
        action: create
        manifest: |
          apiVersion: k6.io/v1alpha1
          kind: TestRun
          metadata:
            name: load-test
          spec:
            initializer:
              nodeSelector:
                cluster: argo
              image: 578061096415.dkr.ecr.us-east-1.amazonaws.com/load-test:1.1.0
              imagePullSecrets:
                - name: dockercred
              securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root  
              volumes:
                 - name: logfolder
                   hostPath:
                    path: /var/log/kaarya
              volumeMounts:
                - mountPath: /tmp
                  name: logfolder    
            starter:   
              nodeSelector:
                cluster: argo
              securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root  
              volumes:
                 - name: logfolder
                   hostPath:
                    path: /var/log/kaarya
              volumeMounts:
                - mountPath: /tmp
                  name: logfolder   
            parallelism: {{workflow.parameters.parallelism}}
            script:
              volumeClaim:
                name: load-test-argo-pvc
                file: {{workflow.parameters.scriptFileName}}
                readOnly: true
            arguments: --tag testid={{workflow.parameters.testId}} --log-output=file=/tmp/load.log --verbose
            runner:
              nodeSelector:
                cluster: argo
              livenessProbe:
                httpGet:
                  path: /v1/status
                  port: 6565
                initialDelaySeconds: 40
                periodSeconds: 10
                timeoutSeconds: 25
                failureThreshold: 6
                successThreshold: 1
              readinessProbe:
                httpGet:
                  path: /v1/status
                  port: 6565
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 25
                failureThreshold: 6
                successThreshold: 1  
              securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root
              resources:
                limits:
                  cpu: 2000m
                  memory: 6148Mi
                requests:
                  cpu: 1000m
                  memory: 2048Mi  
              volumes:
                 - name: logfolder
                   hostPath:
                    path: /var/log/kaarya
              volumeMounts:
                - mountPath: /tmp
                  name: logfolder 
              image: 578061096415.dkr.ecr.us-east-1.amazonaws.com/load-test:1.1.0
              imagePullSecrets:
                - name: dockercred
              imagePullPolicy: Always
              env: 
                - name: DB_USERNAME
                  value: {{workflow.parameters.db_username}}
                - name: DB_PASSWORD
                  value: {{workflow.parameters.db_password}}
                - name: DB_DATABASE
                  value: {{workflow.parameters.db_name}}
                - name: DB_HOST
                  value: {{workflow.parameters.db_host}}
                - name: API_BASE_URL
                  value: {{workflow.parameters.api_base_url}}
                - name: TEST_DEALER_UUID
                  value: {{workflow.parameters.test_dealer_uuid}}
                - name: TEST_DEPARTMENT_UUID
                  value: {{workflow.parameters.test_department_uuid}}
                - name: SERVICE_SUSBCRIBER_USERNAME
                  value: {{workflow.parameters.ss_username}}
                - name: SERVICE_SUSBCRIBER_PASSWORD
                  value: {{workflow.parameters.ss_password}}
                - name: TEST_DEALER_ID
                  value: "{{workflow.parameters.test_dealer_id}}"
                 
  entrypoint: main
  arguments:
    parameters:
      - name: parallelism
      - name: configMapName
      - name: scriptFileName
      - name: testId
      - name: gitlink
      - name: api_base_url
      - name: test_dealer_uuid
      - name: test_department_uuid
      - name: db_host
      - name: db_username
      - name: db_password
      - name: db_name
      - name: ss_username
      - name: ss_password
      - name: test_dealer_id
  serviceAccountName: argo
  ttlStrategy:
    secondsAfterCompletion: 1800
```

### Steps to reproduce the problem

1. Put error in the script
2. run the k6 operator
3. no logs in the file

### Expected behaviour

error logs should come in log file for intializer, starter and runner pods

### Actual behaviour

no logs are coming in file. need to set log output to stdout to look out for errors in scripts
