### ISSUE TITLE
Allow resource requests and limits specification for starter jobs

### ISSUE THREAD

**Issue by seanankenbruck** [grafana/k6-operator#583]
### Feature Description

In kubernetes clusters where the `enforce-resources-as-ratio` kyverno policy is set, starter jobs will fail because the default ratio of limits to requests is greater than the default 2.5x. Here is the default that I see inside the starter pod when deploying version `3.12.0` of the helm chart:

```yaml
Limits:                                                                                                                                                                                                                           
  cpu:     100m                                                                                                                                                                                                                   
  memory:  200Mi                                                                                                                                                                                                                  Requests:                                                                                                                                                                                                                        
  cpu:        50m                                                                                                                                                                                                                 
  memory:     2Mi 
```

In the initializer and runner PodSpec, it is possible to set resource requests and limits via the resources parameter

```go
Resources:       k6.GetSpec().Initializer.Resources
```

This option is not available in the starter PodSpec. Therefore, in a situation where the above kyverno policy is enforced it is not possible to deploy the chart and run k6 jobs inside the cluster without disabling the policy entirely.



### Suggested Solution (optional)

My proposal is to extend support for custom resource requests and limits inside the [starter.go](https://github.com/grafana/k6-operator/blob/main/pkg/resources/jobs/starter.go) job definition file. This will standardize the acceptance across all 3 components (initializer, runner, starter) and allow for seamless deployment into clusters where kyverno policies are strictly enforced. 

### Already existing or connected issues / PRs (optional)

_No response_
