### ISSUE TITLE
Missing metrics using OpenTelemetry output

### ISSUE THREAD

**Issue by davidsaraiva** [grafana/k6-operator#586]
### Brief summary

I recently configured K6, using k6-operator, to push test run metrics in the OpenTelemetry format to Datadog. We were previously using StatsD.
My configuration is pretty simple:

TestRun CRD spec:
```
...
arguments: --tag test_run_id=otel_test_run  --out experimental-opentelemetry
runner:
    env:
      - name: DD_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: K6_OTEL_METRIC_PREFIX
        value: "k6."
      - name: K6_OTEL_GRPC_EXPORTER_INSECURE
        value: "true"
      - name: K6_OTEL_GRPC_EXPORTER_ENDPOINT
        value: "$(DD_AGENT_HOST):4317"
...
```

I am receiving metrics in Datadog but not the sufficient ones to populate the current provided K6 Dashboard, I'm missing some metrics like: 

- k6.http_req_duration.95percentile
- k6.http_req_duration.max
- k6.http_req_sending.95percentile
- ...

Am I missing some kind of configuration?

The Datadog K6 integration tile is in version 1.0.0.

### k6 version

v0.56.0

### OS

Arch Linux

### Steps to reproduce the problem

Run K6 with provided arguments and environment variables and collect OTEL metrics.

### Expected behaviour

Here are some metrics that we had before using StatsD (not all of them are displayed):
![Image](https://github.com/user-attachments/assets/9d107f72-8613-4aab-8a53-e3297eea3085)

### Actual behaviour

These are the metrics I'm currently receiving, in this example I had a different prefix.
![Image](https://github.com/user-attachments/assets/c16bdd06-1e11-42f4-9061-3e2c541c4655)

**Comment by davidsaraiva** [comment]
Hello, sorry for the delay.
I first tested only using the k6-operator, hence the reason for opening this issue here, rather than on k6.

I tested now using k6, only running on a Kubernetes cluster. I changed the prefix so I could see what we were receiving.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test-otel
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: k6-load-test-otel
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: [
          "k6", "run", 
          "--tag", "test_run_id=ds_sample_1", 
          "--out", "experimental-opentelemetry", 
          "/test/script-local.js"
        ]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: test-script
          mountPath: /test
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K6_OTEL_METRIC_PREFIX
          value: "dsk6."
        - name: K6_OTEL_GRPC_EXPORTER_INSECURE
          value: "true"
        - name: K6_OTEL_GRPC_EXPORTER_ENDPOINT
          value: "$(DD_AGENT_HOST):4317"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: test-script
        configMap:
          name: ds-sample-k6-script-cfg
``` 

And I was using a config map containing a very simple script:
```javascript
import http from "k6/http";
import { check } from "k6";


export let options = {
  stages: [
    { duration: '15s', target: 50 },
    { duration: '30s', target: 50 },
    { duration: '15s', target: 0 },
  ],
  thresholds: {
    'http_req_duration': ['p(95)<500'],
  },
};

export default function () {
  let res = http.get('http://target-dummy.load-test-manager:8080/target-dummy/v1/dummy');
  check(res, {
    'status is 200': (r) => r.status === 200,
  });
}
``` 
I am receiving the exact same metrics as the initial comment.
