### ISSUE TITLE
`Unable to retrieve container logs` of initializer

### ISSUE THREAD

**Issue by vipul-mykaarma** [grafana/k6-operator#595]
### Brief summary

I am using 0.0.21 version of k6 operator and 0.55 version of k6 running load tests via argo workflows everything was working fine but suddenly the tests are not working anymore
I see the following errors in k6-operator-controller-manager
```
INFO	controllers.TestRun	Initializer job is ready to start with image `578061096415.dkr.ecr.us-east-1.amazonaws.com/load-test:1.1.0` and command `[sh -c mkdir -p $(dirname /tmp/cdk-ro-old.js.archived.tar) && k6 archive /test/cdk-ro-old.js -O /tmp/cdk-ro-old.js.archived.tar --tag testid=d --log-output=stdout --log-format json 2> /tmp/k6logs && k6 inspect --execution-requirements /tmp/cdk-ro-old.js.archived.tar 2> /tmp/k6logs ; ! cat /tmp/k6logs | grep 'level=error']`	{"namespace": "argo", "name": "load-test", "reconcileID": "b9f5ca7b-63b6-448c-a88b-73ec64a92211"}
2025-06-25T12:24:06Z	INFO	controllers.TestRun	Reconcile(); stage = initialization	{"namespace": "argo", "name": "load-test", "reconcileID": "70f693cf-cfeb-4b70-a20f-1cf19629bff7"}
2025-06-25T12:24:06Z	ERROR	controllers.TestRun	unable to marshal: `unable to retrieve container logs for containerd://e9e8e28b2379db6b58f6a3a9eb6a6b75fb4574694b6dffe92604fac704aaf32f`	{"namespace": "argo", "name": "load-test", "reconcileID": "70f693cf-cfeb-4b70-a20f-1cf19629bff7", "error": "invalid character 'u' looking for beginning of value"}
```

Following are logs of intializer pod : 

```
{
  "paused": null,
  "vus": null,
  "duration": null,
  "iterations": null,
  "stages": null,
  "scenarios": {
    "ramping_arrival_rate": {
      "executor": "ramping-arrival-rate",
      "startTime": null,
      "gracefulStop": null,
      "env": null,
      "exec": null,
      "tags": null,
      "startRate": 10,
      "timeUnit": "1s",
      "stages": [
        {
          "duration": "1m0s",
          "target": 50
        },
        {
          "duration": "1m0s",
          "target": 80
        },
        {
          "duration": "5m0s",
          "target": 100
        },
        {
          "duration": "1m0s",
          "target": 0
        }
      ],
      "preAllocatedVUs": 50,
      "maxVUs": 700
    }
  },
  "executionSegment": null,
  "executionSegmentSequence": null,
  "noSetup": null,
  "setupTimeout": null,
  "noTeardown": null,
  "teardownTimeout": null,
  "rps": null,
  "dns": {
    "ttl": null,
    "select": null,
    "policy": null
  },
  "maxRedirects": null,
  "userAgent": null,
  "batch": null,
  "batchPerHost": null,
  "httpDebug": null,
  "insecureSkipTLSVerify": null,
  "tlsCipherSuites": null,
  "tlsVersion": null,
  "tlsAuth": null,
  "throw": null,
  "thresholds": null,
  "blacklistIPs": null,
  "blockHostnames": null,
  "hosts": null,
  "noConnectionReuse": null,
  "noVUConnectionReuse": null,
  "minIterationDuration": null,
  "ext": null,
  "summaryTrendStats": [
    "avg",
    "min",
    "med",
    "max",
    "p(90)",
    "p(95)"
  ],
  "summaryTimeUnit": null,
  "systemTags": [
    "check",
    "error",
    "error_code",
    "expected_response",
    "group",
    "method",
    "name",
    "proto",
    "scenario",
    "service",
    "status",
    "subproto",
    "tls_version",
    "url"
  ],
  "tags": {
    "testid": "d"
  },
  "metricSamplesBufferSize": null,
  "noCookiesReset": null,
  "discardResponseBodies": null,
  "totalDuration": "8m30s",
  "maxVUs": 700
```

the same script is workin on my qa argo setup where in grafana  k6 operator is 0.0.16

### k6-operator version or image

0.0.21

### Helm chart version (if applicable)

3.13.1

### TestRun / PrivateLoadZone YAML

```
resource:
        action: create
        manifest: |
          apiVersion: k6.io/v1alpha1
          kind: TestRun
          metadata:
            name: load-test
          spec:
            initializer:
              nodeSelector:
                cluster: argo
              image: 578061096415.dkr.ecr.us-east-1.amazonaws.com/load-test:1.1.0
              imagePullSecrets:
                - name: dockercred
               securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root  
            starter:   
              nodeSelector:
                cluster: argo
              securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root  
              volumes:
                 - name: logfolder
                   hostPath:
                    path: /var/log/kaarya
              volumeMounts:
                - mountPath: /tmp
                  name: logfolder   
            parallelism: {{workflow.parameters.parallelism}}
            script:
              volumeClaim:
                name: load-test-argo-pvc
                file: {{workflow.parameters.scriptFileName}}
                readOnly: true
            arguments: --tag testid={{workflow.parameters.testId}} --log-output={{workflow.parameters.log-output}} --verbose --log-format json
            runner:
              nodeSelector:
                cluster: argo
              livenessProbe:
                httpGet:
                  path: /v1/status
                  port: 6565
                initialDelaySeconds: 40
                periodSeconds: 10
                timeoutSeconds: 25
                failureThreshold: 6
                successThreshold: 1
              readinessProbe:
                httpGet:
                  path: /v1/status
                  port: 6565
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 25
                failureThreshold: 6
                successThreshold: 1  
              securityContext:
                runAsNonRoot: false
                runAsUser: 0  # Run as root
                fsGroup: 0    # Set file system group to root
              resources:
                limits:
                  cpu: 2000m
                  memory: 6148Mi
                requests:
                  cpu: 1000m
                  memory: 2048Mi  
              volumes:
                 - name: logfolder
                   hostPath:
                    path: /var/log/kaarya
              volumeMounts:
                - mountPath: /tmp
                  name: logfolder 
              image: 578061096415.dkr.ecr.us-east-1.amazonaws.com/load-test:1.1.0
              imagePullSecrets:
                - name: dockercred
              imagePullPolicy: Always
```

### Steps to reproduce the problem

1. run the argo workflow
2. wait for initializer pod to startup
3. watch out logs of k6-operator-controller-manager
4. runners pods donot start

### Expected behaviour

runner pods should come up 

### Actual behaviour

runners pods are not coming up , load test is not working
