### ISSUE TITLE
Service account passing issue. - Not possible to pull custom image.

### ISSUE THREAD

**Issue by MateuszGrab** [grafana/k6-operator#67]
When trying to apply below Custom Resource with serviceAccount OR serviceAccountName defined, for custom image pull, 
There is the issue with validation.

Yaml CR-k6-test-exec:
`apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  namespace: k6-operator-system
  name: k6-staging-1-vu-test
spec:
  serviceAccount: k6-pull
  parallelism: 1
  script: 
    configMap: 
        name: load-test-staging 
        file: k6-test-order-flow.js
  runner:
    image: <Private Repo>/devops/k6/runner:latest`
    
`kubectl apply -f CR-k6-test-exec -n k6-operator-system`
 
Results:
error: error validating "CR-k6-test-exec": error validating data: ValidationError(K6.spec): unknown field "serviceAccount" in io.k6.v1alpha1.K6.spec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by knmsk** [comment]
Which version are you using?

On `0.0.7-rc2` you can pass the `serviceAccountName` on runner and/or starter spec.
the `serviceAccount` error happened due to the spec of `k6_types.go` didn't match the current CRD.

**Comment by MateuszGrab** [comment]
We were using `0.0.7-rc`. Is there any recommended upgrade strategy to test it with `0.0.7-rc2` ?

**Comment by knmsk** [comment]
I think there is not a special case to upgrade this. the only change between 0.0.7-rc and 0.0.7-rc2 is the starter command and the image that the operator pull. also since `0.0.7-rc` there isn't a `serviceAccount` tag on the spec, only the `serviceAccountName` something like below:
```yaml
kind: K6
metadata:
  namespace: k6-operator-system
  name: k6-staging-1-vu-test
spec:
  parallelism: 1
  script: 
    configMap: 
        name: load-test-staging 
        file: k6-test-order-flow.js
  runner:
    serviceAccountName: k6-pull
    image: <Private Repo>/devops/k6/runner:latest
```
