### ISSUE TITLE
starter container error when using istio

### ISSUE THREAD

**Issue by DrizzlingCattus** [grafana/k6-operator#82]
When i run k6-operator with istio, then starter always change to an error state.

![image](https://user-images.githubusercontent.com/4661295/142447554-4dd146e6-26ac-4937-8a42-9134d87b7c9e.png)

starter pod log:

![image](https://user-images.githubusercontent.com/4661295/142447804-8f83e5ba-6d53-4ca0-90e8-691df3720479.png)

CR file:

```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample-with-extensions
spec:
  parallelism: 4
  script:
    configMap:
      name: crocodile-stress-test
      file: test.js
  arguments: --out prometheus=namespace=k6&port=9090
  ports:
  - containerPort: 9090
    name: metric
  runner:
    image: extension-image:0.0.2
    metadata:
      annotations:
        prometheus.io/scrape: "true"
  scuttle:
    waitForEnvoyTimeout: "20"
```

I can't understand why this is happening. I would like to ask for help if there is any solution.
